### ISSUE TITLE
Make tests work on Browser

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-stats#4]
So, currently, the tests only work on Node.

@dryajov I'm using js-ipfsd-ctl with Go to run the tests because the `js-ipfs` implementation is still lacking some endpoints. How can I make this work on browser? Could you help me with this?

**Comment by dryajov** [comment]
Hi @hacdias, absolutely.

In order to make `ipfsd-ctl` work in the browser, you need to make sure that the REST endpoints are running. The way that is currently done, is through `aegir` hooks, take a look here - https://github.com/ipfs/js-ipfsd-ctl/blob/master/.aegir.js#L16..L21. Take a look at the docs, in case you want to run the endpoints on a different port or tweak some other parameter - https://github.com/ipfs/js-ipfsd-ctl/blob/master/README.md#daemon-factory-class. Hope this helps, and let me know if you have any other questions.

**Comment by hacdias** [comment]
Thank you! 😄
